### ISSUE TITLE
Proposal: Simplify CLI

### ISSUE THREAD

**Issue by joachimschmidt557** [hspak/brightnessztl#7]
Currently, this is the usage of `brightnessztl`:

```
brightnessztl <action> [action-options]

  Actions:
    get:    Display current brightness
    set:    Update the brightness
    debug:  Display backlight information
    help:   Display this

  Set options:
    inc X:   Increase brightness by X%
    dec X:   Decrease brightness by X%
    max:     Set brightness to maximum
    min:     Set brightness to minimum
```

I propose to simplify the `get` and `set` commands:

- Have `get` return a percentage instead of the value, which makes it more inline with `set inc` or `set dec` as those commands deal with percentages
- Replace `set inc X` and `set dec X` with `set +X` and `set -X`
- Introduce `set X` which will set the brightness to `X%`

If this proposal is accepted, I'd be happy to implement it.

**Comment by hspak** [comment]
Sounds good to me! 👍 

I will be happy to merge this change.
